### ISSUE TITLE
Consider loosening to CC-Attribution license

### ISSUE THREAD

**Issue by appsforartists** [SteamDeckHomebrew/wiki#7]
So I know this sounds super dumb, but the corporation I work for claims copyright on everything I do on GitHub while I work there.  There's a process in place to file exemptions, but it's a big endeavor involving lawyers that I can't be bothered to deal with for small patches.

Because they claim copyright, I'm [not supposed to patch repos licensed CC-NonCommercial](https://opensource.google/documentation/reference/thirdparty/licenses#noncommercial).

Would you be amenable to relaxing the license to CC-Attribution and adding a `LICENSE` file to the root of the repo?

CC @liamjones @PartyWumpus @OMGDuke @jurassicplayer @EMERALD0874 @AAGaming00 @TrainDoctor, who as contributors would all have to approve.

**Comment by TrainDoctor** [comment]
Apologies but non-commercial usage is a core value of our operation and I have no interest in undermining that even indirectly. Feel free to file issues suggesting changes and changes can be made. Also as someone who has been in a similar situation, I just wouldn't contribute through my own known personal account!
